//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Transferencias_de_Etiquetas.Entity
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class EtiquetasEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto EtiquetasEntities usando la cadena de conexión encontrada en la sección 'EtiquetasEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public EtiquetasEntities() : base("name=EtiquetasEntities", "EtiquetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EtiquetasEntities.
        /// </summary>
        public EtiquetasEntities(string connectionString) : base(connectionString, "EtiquetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto EtiquetasEntities.
        /// </summary>
        public EtiquetasEntities(EntityConnection connection) : base(connection, "EtiquetasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<etiquetas> etiquetas
        {
            get
            {
                if ((_etiquetas == null))
                {
                    _etiquetas = base.CreateObjectSet<etiquetas>("etiquetas");
                }
                return _etiquetas;
            }
        }
        private ObjectSet<etiquetas> _etiquetas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet etiquetas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToetiquetas(etiquetas etiquetas)
        {
            base.AddObject("etiquetas", etiquetas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Etiquetas_Model", Name="etiquetas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class etiquetas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto etiquetas.
        /// </summary>
        /// <param name="id_etiqueta">Valor inicial de la propiedad id_etiqueta.</param>
        /// <param name="tipo_etiqueta">Valor inicial de la propiedad tipo_etiqueta.</param>
        /// <param name="clave_articulo">Valor inicial de la propiedad clave_articulo.</param>
        /// <param name="fecha_empaque">Valor inicial de la propiedad fecha_empaque.</param>
        /// <param name="fecha_caducidad">Valor inicial de la propiedad fecha_caducidad.</param>
        /// <param name="id_bodega">Valor inicial de la propiedad id_bodega.</param>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="unidad">Valor inicial de la propiedad unidad.</param>
        /// <param name="estatus">Valor inicial de la propiedad estatus.</param>
        public static etiquetas Createetiquetas(global::System.Int64 id_etiqueta, global::System.String tipo_etiqueta, global::System.String clave_articulo, global::System.DateTime fecha_empaque, global::System.DateTime fecha_caducidad, global::System.Int64 id_bodega, global::System.Int64 id_usuario, global::System.Decimal cantidad, global::System.String unidad, global::System.String estatus)
        {
            etiquetas etiquetas = new etiquetas();
            etiquetas.id_etiqueta = id_etiqueta;
            etiquetas.tipo_etiqueta = tipo_etiqueta;
            etiquetas.clave_articulo = clave_articulo;
            etiquetas.fecha_empaque = fecha_empaque;
            etiquetas.fecha_caducidad = fecha_caducidad;
            etiquetas.id_bodega = id_bodega;
            etiquetas.id_usuario = id_usuario;
            etiquetas.cantidad = cantidad;
            etiquetas.unidad = unidad;
            etiquetas.estatus = estatus;
            return etiquetas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_etiqueta
        {
            get
            {
                return _id_etiqueta;
            }
            set
            {
                if (_id_etiqueta != value)
                {
                    Onid_etiquetaChanging(value);
                    ReportPropertyChanging("id_etiqueta");
                    _id_etiqueta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_etiqueta");
                    Onid_etiquetaChanged();
                }
            }
        }
        private global::System.Int64 _id_etiqueta;
        partial void Onid_etiquetaChanging(global::System.Int64 value);
        partial void Onid_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero_etiqueta
        {
            get
            {
                return _numero_etiqueta;
            }
            set
            {
                Onnumero_etiquetaChanging(value);
                ReportPropertyChanging("numero_etiqueta");
                _numero_etiqueta = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero_etiqueta");
                Onnumero_etiquetaChanged();
            }
        }
        private global::System.String _numero_etiqueta;
        partial void Onnumero_etiquetaChanging(global::System.String value);
        partial void Onnumero_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo_etiqueta
        {
            get
            {
                return _tipo_etiqueta;
            }
            set
            {
                Ontipo_etiquetaChanging(value);
                ReportPropertyChanging("tipo_etiqueta");
                _tipo_etiqueta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo_etiqueta");
                Ontipo_etiquetaChanged();
            }
        }
        private global::System.String _tipo_etiqueta;
        partial void Ontipo_etiquetaChanging(global::System.String value);
        partial void Ontipo_etiquetaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_proveedor
        {
            get
            {
                return _id_proveedor;
            }
            set
            {
                Onid_proveedorChanging(value);
                ReportPropertyChanging("id_proveedor");
                _id_proveedor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_proveedor");
                Onid_proveedorChanged();
            }
        }
        private Nullable<global::System.Int32> _id_proveedor;
        partial void Onid_proveedorChanging(Nullable<global::System.Int32> value);
        partial void Onid_proveedorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_lote
        {
            get
            {
                return _id_lote;
            }
            set
            {
                Onid_loteChanging(value);
                ReportPropertyChanging("id_lote");
                _id_lote = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_lote");
                Onid_loteChanged();
            }
        }
        private Nullable<global::System.Int64> _id_lote;
        partial void Onid_loteChanging(Nullable<global::System.Int64> value);
        partial void Onid_loteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> id_pedido
        {
            get
            {
                return _id_pedido;
            }
            set
            {
                Onid_pedidoChanging(value);
                ReportPropertyChanging("id_pedido");
                _id_pedido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_pedido");
                Onid_pedidoChanged();
            }
        }
        private Nullable<global::System.Int64> _id_pedido;
        partial void Onid_pedidoChanging(Nullable<global::System.Int64> value);
        partial void Onid_pedidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave_articulo
        {
            get
            {
                return _clave_articulo;
            }
            set
            {
                Onclave_articuloChanging(value);
                ReportPropertyChanging("clave_articulo");
                _clave_articulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave_articulo");
                Onclave_articuloChanged();
            }
        }
        private global::System.String _clave_articulo;
        partial void Onclave_articuloChanging(global::System.String value);
        partial void Onclave_articuloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_empaque
        {
            get
            {
                return _fecha_empaque;
            }
            set
            {
                Onfecha_empaqueChanging(value);
                ReportPropertyChanging("fecha_empaque");
                _fecha_empaque = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_empaque");
                Onfecha_empaqueChanged();
            }
        }
        private global::System.DateTime _fecha_empaque;
        partial void Onfecha_empaqueChanging(global::System.DateTime value);
        partial void Onfecha_empaqueChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_caducidad
        {
            get
            {
                return _fecha_caducidad;
            }
            set
            {
                Onfecha_caducidadChanging(value);
                ReportPropertyChanging("fecha_caducidad");
                _fecha_caducidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_caducidad");
                Onfecha_caducidadChanged();
            }
        }
        private global::System.DateTime _fecha_caducidad;
        partial void Onfecha_caducidadChanging(global::System.DateTime value);
        partial void Onfecha_caducidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                Onid_bodegaChanging(value);
                ReportPropertyChanging("id_bodega");
                _id_bodega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_bodega");
                Onid_bodegaChanged();
            }
        }
        private global::System.Int64 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int64 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int64 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int64 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String unidad
        {
            get
            {
                return _unidad;
            }
            set
            {
                OnunidadChanging(value);
                ReportPropertyChanging("unidad");
                _unidad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("unidad");
                OnunidadChanged();
            }
        }
        private global::System.String _unidad;
        partial void OnunidadChanging(global::System.String value);
        partial void OnunidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> piezas
        {
            get
            {
                return _piezas;
            }
            set
            {
                OnpiezasChanging(value);
                ReportPropertyChanging("piezas");
                _piezas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("piezas");
                OnpiezasChanged();
            }
        }
        private Nullable<global::System.Int64> _piezas;
        partial void OnpiezasChanging(Nullable<global::System.Int64> value);
        partial void OnpiezasChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estatus
        {
            get
            {
                return _estatus;
            }
            set
            {
                OnestatusChanging(value);
                ReportPropertyChanging("estatus");
                _estatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estatus");
                OnestatusChanged();
            }
        }
        private global::System.String _estatus;
        partial void OnestatusChanging(global::System.String value);
        partial void OnestatusChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tipo_salida
        {
            get
            {
                return _tipo_salida;
            }
            set
            {
                Ontipo_salidaChanging(value);
                ReportPropertyChanging("tipo_salida");
                _tipo_salida = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tipo_salida");
                Ontipo_salidaChanged();
            }
        }
        private global::System.String _tipo_salida;
        partial void Ontipo_salidaChanging(global::System.String value);
        partial void Ontipo_salidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_recepcion
        {
            get
            {
                return _fecha_recepcion;
            }
            set
            {
                Onfecha_recepcionChanging(value);
                ReportPropertyChanging("fecha_recepcion");
                _fecha_recepcion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_recepcion");
                Onfecha_recepcionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_recepcion;
        partial void Onfecha_recepcionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_recepcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_entrega
        {
            get
            {
                return _fecha_entrega;
            }
            set
            {
                Onfecha_entregaChanging(value);
                ReportPropertyChanging("fecha_entrega");
                _fecha_entrega = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_entrega");
                Onfecha_entregaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_entrega;
        partial void Onfecha_entregaChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_entregaChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Etiquetas_Model", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="username">Valor inicial de la propiedad username.</param>
        /// <param name="password">Valor inicial de la propiedad password.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="id_area">Valor inicial de la propiedad id_area.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static usuarios Createusuarios(global::System.Int32 id_usuario, global::System.String username, global::System.String password, global::System.String nombre, global::System.Int64 id_area, global::System.Boolean estado)
        {
            usuarios usuarios = new usuarios();
            usuarios.id_usuario = id_usuario;
            usuarios.username = username;
            usuarios.password = password;
            usuarios.nombre = nombre;
            usuarios.id_area = id_area;
            usuarios.estado = estado;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_area
        {
            get
            {
                return _id_area;
            }
            set
            {
                Onid_areaChanging(value);
                ReportPropertyChanging("id_area");
                _id_area = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_area");
                Onid_areaChanged();
            }
        }
        private global::System.Int64 _id_area;
        partial void Onid_areaChanging(global::System.Int64 value);
        partial void Onid_areaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Boolean _estado;
        partial void OnestadoChanging(global::System.Boolean value);
        partial void OnestadoChanged();

        #endregion

    
    }

    #endregion

    
}
