//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Transferencias_de_Etiquetas.WS_Friolala {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioWebSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioWeb : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarEtiquetasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioWeb() {
            this.Url = global::Transferencias_de_Etiquetas.Properties.Settings.Default.Transferencias_de_Etiquetas_WS_Friolala_ServicioWeb;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarEtiquetasCompletedEventHandler ConsultarEtiquetasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarEtiquetas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EtiquetasGrid[] ConsultarEtiquetas(string NumerosDeEtiquetas) {
            object[] results = this.Invoke("ConsultarEtiquetas", new object[] {
                        NumerosDeEtiquetas});
            return ((EtiquetasGrid[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarEtiquetasAsync(string NumerosDeEtiquetas) {
            this.ConsultarEtiquetasAsync(NumerosDeEtiquetas, null);
        }
        
        /// <remarks/>
        public void ConsultarEtiquetasAsync(string NumerosDeEtiquetas, object userState) {
            if ((this.ConsultarEtiquetasOperationCompleted == null)) {
                this.ConsultarEtiquetasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarEtiquetasOperationCompleted);
            }
            this.InvokeAsync("ConsultarEtiquetas", new object[] {
                        NumerosDeEtiquetas}, this.ConsultarEtiquetasOperationCompleted, userState);
        }
        
        private void OnConsultarEtiquetasOperationCompleted(object arg) {
            if ((this.ConsultarEtiquetasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarEtiquetasCompleted(this, new ConsultarEtiquetasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EtiquetasGrid {
        
        private string numeroDeEtiquetaField;
        
        private string tipoEtiquetaField;
        
        private System.Nullable<int> idProveedorField;
        
        private System.Nullable<long> idLoteField;
        
        private System.Nullable<long> idPedidoField;
        
        private string claveField;
        
        private string claveNombreField;
        
        private System.DateTime fechaDeEmpaqueField;
        
        private System.DateTime fechaDeCaducidadField;
        
        private decimal cantidadField;
        
        private string unidadField;
        
        private System.Nullable<long> piezasField;
        
        private System.Nullable<System.DateTime> fechaDeRecepcionField;
        
        /// <comentarios/>
        public string NumeroDeEtiqueta {
            get {
                return this.numeroDeEtiquetaField;
            }
            set {
                this.numeroDeEtiquetaField = value;
            }
        }
        
        /// <comentarios/>
        public string TipoEtiqueta {
            get {
                return this.tipoEtiquetaField;
            }
            set {
                this.tipoEtiquetaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> IdProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                this.idProveedorField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> IdPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
            }
        }
        
        /// <comentarios/>
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
            }
        }
        
        /// <comentarios/>
        public string ClaveNombre {
            get {
                return this.claveNombreField;
            }
            set {
                this.claveNombreField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaDeEmpaque {
            get {
                return this.fechaDeEmpaqueField;
            }
            set {
                this.fechaDeEmpaqueField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaDeCaducidad {
            get {
                return this.fechaDeCaducidadField;
            }
            set {
                this.fechaDeCaducidadField = value;
            }
        }
        
        /// <comentarios/>
        public decimal Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <comentarios/>
        public string Unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Piezas {
            get {
                return this.piezasField;
            }
            set {
                this.piezasField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaDeRecepcion {
            get {
                return this.fechaDeRecepcionField;
            }
            set {
                this.fechaDeRecepcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultarEtiquetasCompletedEventHandler(object sender, ConsultarEtiquetasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarEtiquetasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarEtiquetasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EtiquetasGrid[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EtiquetasGrid[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591